language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
before_script:
- bin/./install-solr.sh
- npm install -g istanbul
- npm install -g mocha
script: make test
after_success:
- make coveralls
